config/routes.rb
Rails.application.routes.draw do
  resources :games
  resources :vessels
  resources :players

  # GAMES

  post '/game/:game_id/place/:player_id/:vessel_type/:y/:x' => 'games#place_vessels'

  post '/games/new/:game_name/:player1/:player2' => 'games#create'

  get '/game/:game_id/score' => 'games#score'

  post '/game/:game_id/shoot/:enemy_player_id/:y/:x' => 'games#shoot'

  post '/game/:game_id/reset' => 'games#reset'


  # VESSELS

  post '/vessel/create/:vessel_type/:vessel_name/:y/:x/player/:player_id' => 'vessels#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
    has_many :players
    has_many :vessels

    # TODO: add validations
end

app/models/player.rb
class Player < ApplicationRecord
    has_many :vessels

    # TODO: add validations
end

app/models/vessel.rb
class Vessel < ApplicationRecord
    belongs_to :player
    has_many :vessel_locations

    def size
        case self.vessel_type
        when 'CARRIER'
            5
        when 'BATTLESHIP'
            4
        when 'DESTROYER'
            3
        when 'SUBMARINE'
            3
        when 'PATROL BOAT'
            2
        when 'PLANE'
            3
        end
    end

    # TODO: add validations
    
end

app/models/vessel_location.rb
class VesselLocation < ApplicationRecord
    belongs_to :vessel

    # TODO: put constraints on vessel_locations based on vessel_type

    # validates :x, uniqueness: true
    # validates :y, uniqueness: true

    validates_inclusion_of :x, :in => 1..10
    validates_inclusion_of :y, :in => ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


    # validates :x, uniqueness: true, unless: ->validates :y, uniqueness: true
    # validates :y, uniqueness: true, unless: ->validates :x, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  skip_before_action :verify_authenticity_token

  # POST localhost:3000/games/new/:game_name/:player1/:player2
  def create
    @game = Game.create(name: params[:game_name])
    Player.create(name: params[:player1], game_id: @game.id)
    Player.create(name: params[:player2], game_id: @game.id)
    render plain: "Game created."
  end

  # POST /game/:game_id/place/:player_id/:vessel_type/:y/:x
  def place_vessel
    @vessel = Vessel.find_by(player_id: params[:player_id], vessel_type: params[:vessel_type])
    @location = VesselLocation.create(x: params[:x], y: params[:y], vessel_id: @vessel.id)
  end

  # POST /game/:game_id/shoot/:enemy_player_id/:y/:x
  def shoot
    @player = Player.find(params[:enemy_player_id])
    @vessels = @player.vessels
    @vessels.each do |vessel|
      vessel.vessel_locations.each do |location|
        puts "x = #{location.x}"
        puts "y = #{location.y}"
        puts "#{params[:x].to_i == location.x}"
        puts "#{params[:y] == location.y}"
        if location.x == params[:x].to_i && location.y == params[:y]
          @player.update(score: @player.score += 1)
          vessel.update(damage: vessel.damage += 1)
          if vessel.damage >= vessel.size
            vessel.update(status: 'SUNK')
            puts "SUNK"
            score("SUNK", @player.name)
          else
            puts "HIT" 
            score("HIT", @player.name)
          end
        else
          puts "MISS"
          score("MISS", @player.name)
        end
      end
    end
  end

  # GET /game/:game_id/score
  def score(string="", enemy="")
    @game = Game.find(params[:game_id])
    @player1_score = Player.find(@game.players.first.id).score
    @player2_score = Player.find(@game.players.last.id).score
    if enemy != ""
      render plain: "Player 1: #{@player1_score} | Player 2: #{@player2_score} \n SHOT FIRED AT #{enemy} - #{string}!"
    else
      render plain: "Player 1: #{@player1_score} | Player 2: #{@player2_score}"
    end
  end

  # POST /game/:game_id/reset
  def reset
    @game = Game.find(params[:game_id])
    @game.players.each do |player|
      player.update(score: 0)
      player.vessels.each do |vessel|
        vessel.update(damage: 0, status: "ALIVE")
      end
    end
    puts "RESET SCORE"
    score()
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
end

app/controllers/vessels_controller.rb
class VesselsController < ApplicationController
  skip_before_action :verify_authenticity_token

  # GET /vessels/new
  def new
    @vessel = Vessel.new()
  end

  # POST /vessel/create/:vessel_type/:vessel_name/:y/:x/player/:player_id
  def create
    @vessel = Vessel.create(player_id: params[:player_id], vessel_type: params[:vessel_type], name: params[:vessel_name], damage: 0)
    @location = VesselLocation.create(x: params[:x], y: params[:y], vessel_id: @vessel.id)
    if @location.save
      render plain: "Vessel #{@vessel.name} created for player #{params[:player_id]} at #{@location.y}, #{@location.x}!"
    else
      render plain: "Location taken or out of range. Try again."
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/vessels_helper.rb
module VesselsHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Player 1 name
    <%= form.text_field :player1 %>
  </div>

  <div class="field">
    Player 2 name
    <%= form.text_field :player2 %>
  </div>

  <div class="field">
    Game Name
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Has many</th>
      <th>Has many</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.has_many %></td>
        <td><%= game.has_many %></td>
        <td><%= game.name %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Player 1:</strong>
  <%= @player1.name %>
</p>

<p>
  <strong>Player 2:</strong>
  <%= @player2.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Battleship</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Players</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>

app/views/vessels/_form.html.erb
<%= form_with(model: vessel, local: true) do |form| %>
  <% if vessel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vessel.errors.count, "error") %> prohibited this vessel from being saved:</h2>

      <ul>
      <% vessel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.number_field :size %>
  </div>

  <div class="field">
    Player ID
    <%= form.number_field :player_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vessels/edit.html.erb
<h1>Editing Vessel</h1>

<%= render 'form', vessel: @vessel %>

<%= link_to 'Show', @vessel %> |
<%= link_to 'Back', vessels_path %>

app/views/vessels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vessels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Size</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vessels.each do |vessel| %>
      <tr>
        <td><%= vessel.name %></td>
        <td><%= vessel.size %></td>
        <td><%= link_to 'Show', vessel %></td>
        <td><%= link_to 'Edit', edit_vessel_path(vessel) %></td>
        <td><%= link_to 'Destroy', vessel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vessel', new_vessel_path %>

app/views/vessels/new.html.erb
<h1>New Vessel</h1>

<%= render 'form', vessel: @vessel %>

<%= link_to 'Back', vessels_path %>

app/views/vessels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vessel.name %>
</p>

<p>
  <strong>Size:</strong>
  <%= @vessel.size %>
</p>

<%= link_to 'Edit', edit_vessel_path(@vessel) %> |
<%= link_to 'Back', vessels_path %>